name: warasoft-chat
services:
- name: backend
  github:
    branch: main
    deploy_on_push: true
    repo: su-repo/nombre-del-repo  # Actualizar con tu repositorio
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "3000"
  - key: NODE_ENV
    scope: RUN_TIME
    value: "production" 